[DRFT-515] Add rbac notifications read
RedHatInsights/system-baseline-backend pull request #188
Opened 2021-06-24 15:00 UTC by CodeHeeler

## Secure Coding Practices Checklist Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [ ] Input Validation
- [ ] Output Encoding
- [ ] Authentication and Password Management
- [ ] Session Management
- [ ] Access Control
- [ ] Cryptographic Practices
- [ ] Error Handling and Logging
- [ ] Data Protection
- [ ] Communication Security
- [ ] System Configuration
- [ ] Database Security
- [ ] File Management
- [ ] Memory Management
- [ ] General Coding Practices

2021-06-25 15:37 UTC, petrblaho commented on system_baseline/views/v1.py
> +from system_baseline.global_helpers import ensure_rbac_baselines_write, ensure_rbac_notifications_read, ensure_rbac_notifications_write
Missing import of `ensure_rbac_badeline_read`

2021-06-25 15:38 UTC, petrblaho requested changes
I found that one method of not imported.

2021-06-25 18:06 UTC, CodeHeeler commented
> I found that one method of not imported.

Ah! thanks!  I noticed it wasn't when I added my imports, but later when I added the call in the methods below, I forgot to go back and add it at the top.  Also forgot to do black/flake8 to handle the run on line there so I'll take care of those now and push up again.

2021-06-30 20:17 UTC, fellipeh approved these changes
LGTM

2021-07-01 18:23 UTC, merged